keboola/output-mapping

- Configuration/Table/Manifest.php
- Tests/OutputTableConfigurationTest.php
fixes https://github.com/keboola/docker-bundle/issues/256
> feat: make delete_where_op setting more permissive

- Tests/StorageApiWriterMetadataTest.php
- Writer/Writer.php
- composer.json
fixes https://github.com/keboola/output-mapping/issues/26
doesn't solve https://github.com/keboola/docker-bundle/issues/216 that'll come in next PR
> fix: make sure to add the correct column to storage

- DeferredTasks/LoadTableQueue.php
- Tests/StorageApiHeadlessWriterTest.php
- Tests/StorageApiWriterTest.php
feat: publish task count, required for https://github.com/keboola/docker-bundle/issues/377
> publish task count

- Dockerfile
- src/DeferredTasks/LoadTableQueue.php
- src/Exception/InvalidOutputException.php
- src/Writer/FileWriter.php
- src/Writer/TableWriter.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/StorageApiHeadlessWriterTest.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
This should help solve #47 and will make it possible to fix PS-119 https://keboola.atlassian.net/browse/PS-119
I've refactored the tests here also, using minimum values for sapi-client backoff and poll delay should help speed up the tests somewhat.
> File not found should have error code 404

- composer.json
- src/Writer/FileWriter.php
- src/Writer/Helper/ConfigurationMerger.php
- src/Writer/TableWriter.php
- tests/Writer/Helper/ConfigurationMergerTest.php
- tests/Writer/StorageApiHeadlessWriterTest.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/WriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-285
miro: neni to hotovy, chybi tomu jeste dost testu. ale je to dost zamotany, tak davam na takovy predcasny review, jestli neuvidis neco co prehlizim, cim by se to dalo zjednodusit
> output mapping to workspace

- .env.template
- README.md
- composer.json
- docker-compose.yml
- src/Writer/TableWriter.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
- tests/Writer/Helper/PrimaryKeyHelperTest.php
- tests/Writer/StorageApiHeadlessWriterTest.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
- tests/Writer/WriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-705
> PS-705 Synapse workspace

- .gitignore
- src/Writer/TableWriter.php
- tests/Writer/Helper/ConfigurationMergerTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
- tests/Writer/WriterWorkspaceTest.php
The actual fix is the two lines in TableWriter.php.
There is actually no change in ConfigurationMergerTest.php it was just confusing without the keys.
https://keboola.atlassian.net/browse/PS-983
> fix: incremental flag

- docker-compose.yml
- docker/xdebug/Dockerfile
https://keboola.atlassian.net/browse/PS-1170
> PS-1170 dev improvements

- README.md
- composer.json
- src/Writer/AbstractWriter.php
- src/Writer/FileWriter.php
- src/Writer/TableWriter.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
- tests/Writer/StorageApiHeadlessWriterTest.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
- tests/Writer/WriterWorkspaceTest.php
Use two storage clients
https://keboola.atlassian.net/browse/PS-1170
> Client wrapper

- src/Writer/Helper/DestinationRewriter.php
- src/Writer/TableWriter.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/Helper/DestinationRewriterTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-1497
> feat: use branch bucket for branch jobs

- composer.json
- src/Writer/TableWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
Just doing tables for now.  Files will be in the nest PR
> PS-1154 ABS workspace for tables

- tests/Writer/SynapseWriterWorkspaceTest.php
fixes to synapse tests that slipped because they were disabled
> fix: synapse test

- bootstrap.php
- composer.json
- src/Writer/Helper/DestinationRewriter.php
- src/Writer/TableWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
- tests/Writer/CreateBranchTrait.php
- tests/Writer/Helper/DestinationRewriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
- tests/Writer/WriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-1533
> distinguish between branch name and branch id

- src/Writer/FileWriter.php
- src/Writer/Helper/TagsRewriter.php
- tests/Writer/Helper/TagsRewriterTest.php
- tests/Writer/StorageApiWriterTest.php
Fixes: https://keboola.atlassian.net/browse/PS-1563
V dev branchi prefixuje vsechny tagy
> Tags prefix

- composer.json
- src/Writer/FileWriter.php
- tests/Writer/SynapseWriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-1574
> PS-1574 update to latest IM

- .env.template
- docker-compose.yml
Pouziva se v testech ale nebyl v env template ani docker compose
> env STORAGE_API_TOKEN_MASTER

- src/Writer/Helper/DestinationRewriter.php
- src/Writer/Helper/TagsRewriter.php
- tests/Writer/Helper/DestinationRewriterTest.php
- tests/Writer/Helper/TagsRewriterTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/WriterWorkspaceTest.php
Fixes: https://keboola.atlassian.net/browse/PS-1581
> Dev mode - prefix with branch id

- composer.json
- src/Writer/FileWriter.php
Moc rychle mergujes, ja to nemel jeste hotove po tom upgradu input mappingu
> fixup for keboola/input-mapping 11.1.0

- composer.json
- src/Writer/FileWriter.php
Fixes: https://keboola.atlassian.net/browse/KBC-1159
> Input mapping update - 11.2.0

- composer.json
- src/Writer/FileWriter.php
- src/Writer/TableWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
- tests/Writer/StorageApiHeadlessWriterTest.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterMetadataTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
update to new IM namespaces
https://keboola.atlassian.net/browse/PS-1630
follow up to https://github.com/keboola/input-mapping/pull/77
> update IM interface

- src/Writer/TableWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/BaseWriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-1647
Checks if the source is a directory and if so, it loads the directory contents as slices.
> Support sliced files in ABS table output mapping 

- src/Writer/TableWriter.php
- tests/Writer/WriterWorkspaceTest.php
apparently I was too hotheaded in https://github.com/keboola/output-mapping/pull/72/files
https://keboola.atlassian.net/browse/PS-1663
> fix: resolve destination when bucket is specified in configuration, but destination is not

- src/Writer/TableWriter.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/WriterWorkspaceTest.php
https://keboola.atlassian.net/browse/PS-1695
> disallow writing to production buckets in dev mode

- src/Writer/AbstractWriter.php
- src/Writer/FileWriter.php
- src/Writer/Helper/TagsHelper.php
- src/Writer/Helper/TagsRewriter.php
- src/Writer/TableWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/Helper/TagsHelperTest.php
- tests/Writer/StorageApiWriterTest.php
https://keboola.atlassian.net/browse/PS-1784
> PS-1784 Add system metadata tags to files

- src/Writer/AbstractWriter.php
- src/Writer/FileWriter.php
- src/Writer/Helper/TagsHelper.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/StorageApiWriterTest.php
I switched argument order to allow for default.
> PS-1855 optional metadata + runId

- src/Writer/FileWriter.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/BaseWriterTest.php
- tests/Writer/File/Strategy/ABSWorkspaceTest.php
- tests/Writer/StorageApiWriterTest.php
- tests/Writer/SynapseWriterWorkspaceTest.php
The other end of https://github.com/keboola/input-mapping/pull/89, but it's independent of it.
> PS-1798 Add branch prefix to processed tags

- src/Configuration/Table.php
- src/Writer/TableWriter.php
- tests/Configuration/TableTest.php
https://keboola.atlassian.net/browse/PS-2089
> PS-2089 Add table.file-tags config

- azure-pipelines.yml
https://keboola.atlassian.net/browse/PS-1890
> PS-1890 Run CI on PHP 5.6 & 7.4 in parallel

- .dockerignore
- composer.json
- src/Writer/TableWriter.php
- tests/Writer/StorageApiSlicedWriterTest.php
- tests/Writer/StorageApiWriterTest.php
https://keboola.atlassian.net/browse/PS-2388
> feat: tag staging files

- composer.json
- src/Staging/StrategyFactory.php
- src/Writer/Table/TableWriterV1.php
- src/Writer/Table/TableWriterV2.php
- tests/Staging/StrategyFactoryTest.php
https://keboola.atlassian.net/browse/PS-2465
Ono to sice ještě nefunguje, ale říkám si, že když se tohle mergne, tak to nic nerozbije.
> feat: add exasol staging

- composer.json
replaces https://github.com/keboola/output-mapping/pull/91
> use prod dependency

- src/Writer/Table/TableConfigurationResolver.php
- src/Writer/Table/TableWriterV2.php
- tests/Writer/StorageApiLocalTableWriterV2Test.php
https://keboola.atlassian.net/browse/PS-2507
> PS-2596 Allow falling back to source name as a destination

- composer.json
- src/DeferredTasks/LoadTableQueue.php
- src/Table/Result.php
- tests/DeferredTasks/LoadTableQueueTest.php
- tests/Table/ResultTest.php
- tests/Writer/StorageApiLocalTableWriterV1Test.php
- tests/Writer/StorageApiLocalTableWriterV2Test.php
Fixes: https://keboola.atlassian.net/browse/PS-2619
> Table results

- src/Writer/Table/MappingDestination.php
- tests/Writer/Table/MappingDestinationTest.php
https://keboola.atlassian.net/browse/PS-2684
> fix: removal of c- prefix 

- azure-pipelines.yml
- composer.json
- docker-compose.yml
- src/Configuration/File.php
- src/Configuration/File/Manifest.php
- src/Configuration/Table.php
- src/Configuration/Table/Manifest.php
- src/Configuration/TableFile.php
Fixes: https://keboola.atlassian.net/browse/PS-3141
drop PHP5.6 support
> drop PHP5.6 support

- composer.json
- src/Writer/File/Strategy/ABSWorkspace.php
- src/Writer/Table/Strategy/AbsWorkspaceTableStrategy.php
- tests/Configuration/TableTest.php
- tests/Writer/AbsWriterWorkspaceTest.php
- tests/Writer/File/Strategy/ABSWorkspaceTest.php
Fixes https://keboola.atlassian.net/browse/PS-3052
> ABS client initialization fixup

- composer.json
- src/DeferredTasks/Metadata/ColumnMetadata.php
- src/DeferredTasks/Metadata/TableMetadata.php
Fixes: https://keboola.atlassian.net/browse/PS-3117
Bulk column metadata update
> Bulk column metadata update

- composer.json
- src/DeferredTasks/Metadata/ColumnMetadata.php
- src/DeferredTasks/Metadata/TableMetadata.php
Reverts keboola/output-mapping#106
https://keboola.slack.com/archives/CQB468K63/p1645182883911199
> Revert "Bulk column metadata update"

- composer.json
- src/DeferredTasks/Metadata/ColumnMetadata.php
- src/DeferredTasks/Metadata/TableMetadata.php
This reverts commit 16604b01c4f6a4f20072bf5e1b997a97b4840334, reversing
changes made to c63bcf2650a912a198f9108782b88cb1dd64f295.
> Revert "Merge pull request #107 from keboola/revert-106-erik-PS-3117"

- composer.json
- src/Staging/StrategyFactory.php
- tests/Staging/StrategyFactoryTest.php
Fixes: https://keboola.atlassian.net/browse/PS-3402
> Teradata Staging Strategy

- src/DeferredTasks/TableWriter/CreateAndLoadTableTask.php
- src/DeferredTasks/TableWriter/LoadTableTask.php
- tests/DeferredTasks/CreateAndLoadTableTaskTest.php
- tests/DeferredTasks/LoadTableTaskTest.php
https://keboola.atlassian.net/browse/PS-3508
> PS-3508 Switch 403 to user exception
